services:
  mariadb:
    container_name: mariadb
    image: mariadb
    env_file: .env
    build:  requirements/mariadb/.
    networks:
      - inc
    volumes:
      - db:/var/lib/mysql
    restart: on-failure
  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    env_file: .env
    build:  requirements/wordpress/.
    networks:
      - inc
    volumes:
      - wp:/var/www/html
    restart: on-failure
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    env_file: .env
    build:  requirements/nginx/.
    ports:
      - 443:443
    networks:
      - inc
    volumes:
      - wp:/var/www/html
    restart: on-failure
networks:
  inc:
volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yzoullik/data/wp
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yzoullik/data/db